spring:
  application:
    name: spring-admin
  profiles:
    default: local
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      indent_output: true
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mvc:
    problemdetails:
      enabled: true

server:
  port: 9800
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  observations:
    key-values:
      org: ${spring.application.org}
  metrics:
    tags:
      application: ${spring.application.name}
      org: ${spring.application.org}
      profiles: ${spring.profiles.active}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        step: 10s
  tracing:
    sampling:
      probability: 1.0

spring.cloud.discovery.client:
  composite-indicator:
    enabled: false

logging:
  level:
    com.netflix.discovery: OFF
  file:
    name: ${spring.application.home:.}/logs/${spring.application.name}.log