server:
  port: 9903
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true
infrastructure:
  kafka_brokers: ${INFRA_KAFKA_BROKERS:127.0.0.1:9092}
  topic: stock-transactions
  redis:
    host: localhost
    port: 6379
spring:
  zipkin:
    base-url:http://localhost:9411
  datasource:
    url: jdbc:postgresql://${INFRA_POSTGRES_HOST:localhost}:${INFRA_POSTGRES_PORT:32432}/demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
