server:
  port: 9900
eureka:
  renewalPercentThreshold: 0.49
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    max-threads-for-peer-replication: 0
    wait-time-in-ms-when-sync-empty: 0
    enableSelfPreservation: false
  instance:
    lease-renewal-interval-in-seconds: 0
spring:
  datasource:
    url: jdbc:h2:mem:batchjobs;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver

