eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9900/eureka}
  instance:
    preferIpAddress: true
infrastructure:
  kafka_brokers: ${INFRA_KAFKA_BROKERS:127.0.0.1:9092}
  redis:
    host: localhost
    keys:
      indices: indices
      portfolio: portfolio
      stocks: stocks
    port: 6379
  services:
    auth:
      host-name: AUTH-SERVICE
  topics:
    orders-placed: orders
logging:
  file:
    name: ${spring.application.home:.}/logs/${spring.application.name}.log
  level:
    com.netflix.discovery: false
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          requests: true
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
server:
  port: 9903
spring:
  application:
    name: order-service
  boot:
    admin:
      client:
        url: http://localhost:9800
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://${INFRA_POSTGRES_HOST:localhost}:${INFRA_POSTGRES_PORT:5432}/stocks
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true
