server:
  port: 9905
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '/api/*'
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          requests: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true
infrastructure:
  kafka_brokers: ${INFRA_KAFKA_BROKERS:127.0.0.1:9092}
  topic: stock-transactions
spring:
  datasource:
    url: jdbc:postgresql://${INFRA_POSTGRES_HOST:localhost}:${INFRA_POSTGRES_PORT:5432}/demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'