server:
  port: 9905
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true
infrastructure:
  kafka_brokers: ${INFRA_KAFKA_BROKERS:127.0.0.1:9092}
  topic: stock-transactions
  redis:
    host: ${INFRA_REDIS_HOST:localhost}
    port: ${INFRA_REDIS_PORT:6379}
    keys:
      stocks: "stocks"
      indices: "indices"
      portfolio: "portfolio"
spring:
  datasource:
    url: jdbc:postgresql://${INFRA_POSTGRES_HOST:localhost}:${INFRA_POSTGRES_PORT:32432}/demo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
